// Code generated by protoc-gen-go.
// source: recharge.proto
// DO NOT EDIT!

/*
Package recharge is a generated protocol buffer package.

It is generated from these files:
	recharge.proto

It has these top-level messages:
	RegisterRequest
	RegisterReply
*/
package recharge

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type RegisterRequest struct {
	Phone      string `protobuf:"bytes,1,opt,name=phone" json:"phone,omitempty"`
	Email      string `protobuf:"bytes,2,opt,name=email" json:"email,omitempty"`
	InviteCode string `protobuf:"bytes,3,opt,name=invite_code,json=inviteCode" json:"invite_code,omitempty"`
	Passwd     string `protobuf:"bytes,4,opt,name=passwd" json:"passwd,omitempty"`
}

func (m *RegisterRequest) Reset()                    { *m = RegisterRequest{} }
func (m *RegisterRequest) String() string            { return proto.CompactTextString(m) }
func (*RegisterRequest) ProtoMessage()               {}
func (*RegisterRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *RegisterRequest) GetPhone() string {
	if m != nil {
		return m.Phone
	}
	return ""
}

func (m *RegisterRequest) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *RegisterRequest) GetInviteCode() string {
	if m != nil {
		return m.InviteCode
	}
	return ""
}

func (m *RegisterRequest) GetPasswd() string {
	if m != nil {
		return m.Passwd
	}
	return ""
}

type RegisterReply struct {
	Ok  bool   `protobuf:"varint,1,opt,name=ok" json:"ok,omitempty"`
	Id  string `protobuf:"bytes,2,opt,name=id" json:"id,omitempty"`
	Msg string `protobuf:"bytes,3,opt,name=msg" json:"msg,omitempty"`
}

func (m *RegisterReply) Reset()                    { *m = RegisterReply{} }
func (m *RegisterReply) String() string            { return proto.CompactTextString(m) }
func (*RegisterReply) ProtoMessage()               {}
func (*RegisterReply) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *RegisterReply) GetOk() bool {
	if m != nil {
		return m.Ok
	}
	return false
}

func (m *RegisterReply) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *RegisterReply) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

func init() {
	proto.RegisterType((*RegisterRequest)(nil), "recharge.RegisterRequest")
	proto.RegisterType((*RegisterReply)(nil), "recharge.RegisterReply")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for User service

type UserClient interface {
	Register(ctx context.Context, in *RegisterRequest, opts ...grpc.CallOption) (*RegisterReply, error)
}

type userClient struct {
	cc *grpc.ClientConn
}

func NewUserClient(cc *grpc.ClientConn) UserClient {
	return &userClient{cc}
}

func (c *userClient) Register(ctx context.Context, in *RegisterRequest, opts ...grpc.CallOption) (*RegisterReply, error) {
	out := new(RegisterReply)
	err := grpc.Invoke(ctx, "/recharge.User/Register", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for User service

type UserServer interface {
	Register(context.Context, *RegisterRequest) (*RegisterReply, error)
}

func RegisterUserServer(s *grpc.Server, srv UserServer) {
	s.RegisterService(&_User_serviceDesc, srv)
}

func _User_Register_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServer).Register(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/recharge.User/Register",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServer).Register(ctx, req.(*RegisterRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _User_serviceDesc = grpc.ServiceDesc{
	ServiceName: "recharge.User",
	HandlerType: (*UserServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Register",
			Handler:    _User_Register_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "recharge.proto",
}

func init() { proto.RegisterFile("recharge.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 209 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x6c, 0x90, 0xbd, 0x4a, 0xc0, 0x30,
	0x14, 0x85, 0x6d, 0x5a, 0x4b, 0xbd, 0x62, 0x95, 0x8b, 0x68, 0x74, 0x51, 0x3a, 0x39, 0x75, 0xd0,
	0x17, 0x50, 0x5c, 0x9c, 0x03, 0xce, 0x52, 0x9b, 0x4b, 0x1b, 0xfa, 0x93, 0x98, 0xc4, 0x4a, 0xdf,
	0x5e, 0x9a, 0xb6, 0x0a, 0xe2, 0x96, 0xef, 0x1c, 0xc8, 0xc7, 0xb9, 0x90, 0x5b, 0xaa, 0xdb, 0xca,
	0x36, 0x54, 0x1a, 0xab, 0xbd, 0xc6, 0x6c, 0xe7, 0x62, 0x82, 0x53, 0x41, 0x8d, 0x72, 0x9e, 0xac,
	0xa0, 0x8f, 0x4f, 0x72, 0x1e, 0xcf, 0xe1, 0xd0, 0xb4, 0x7a, 0x24, 0x1e, 0xdd, 0x46, 0x77, 0x47,
	0x62, 0x85, 0x25, 0xa5, 0xa1, 0x52, 0x3d, 0x67, 0x6b, 0x1a, 0x00, 0x6f, 0xe0, 0x58, 0x8d, 0x93,
	0xf2, 0xf4, 0x56, 0x6b, 0x49, 0x3c, 0x0e, 0x1d, 0xac, 0xd1, 0xb3, 0x96, 0x84, 0x17, 0x90, 0x9a,
	0xca, 0xb9, 0x2f, 0xc9, 0x93, 0xd0, 0x6d, 0x54, 0x3c, 0xc1, 0xc9, 0xaf, 0xd7, 0xf4, 0x33, 0xe6,
	0xc0, 0x74, 0x17, 0x94, 0x99, 0x60, 0xba, 0x5b, 0x58, 0xc9, 0x4d, 0xc6, 0x94, 0xc4, 0x33, 0x88,
	0x07, 0xd7, 0x6c, 0x86, 0xe5, 0x79, 0xff, 0x02, 0xc9, 0xab, 0x23, 0x8b, 0x8f, 0x90, 0xed, 0x5f,
	0xe1, 0x55, 0xf9, 0xb3, 0xf4, 0xcf, 0xac, 0xeb, 0xcb, 0xff, 0x2a, 0xd3, 0xcf, 0xc5, 0xc1, 0x7b,
	0x1a, 0xae, 0xf2, 0xf0, 0x1d, 0x00, 0x00, 0xff, 0xff, 0xd8, 0x32, 0x1d, 0xe9, 0x27, 0x01, 0x00,
	0x00,
}
